---

# workaround for https://github.com/ansible/ansible/issues/45223
- name: poll vm facts until IP address is available
  tags: start-vm
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname | default(omit) }}"
    username: "{{ vcenter_username | default(omit) }}"
    password: "{{ vcenter_password | default(omit) }}"
    validate_certs: "{{ vcenter_validate_certs | default(omit) }}"
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vm_guestname }}"
  delegate_to: localhost
  register: wait_facts
  until: wait_facts.instance.ipv4 is not none
  retries: 18
  delay: 5

# vim: ts=2:sw=2:noautoindent:nosmartindent
